### ISSUE TITLE
APP does not work on Win10 and Win11

### ISSUE THREAD

**Issue by Hansi99** [caesiumstudio/csBooks-updates#28]
I bought an app from the windows store. Yes i have paid for it !!  At first it works rightly but now, id ont know why,  I am not able to run it properly ( on Win10 and Win 11 ) because it hangs at the "Generatig Book Thumbnails"
![Error](https://user-images.githubusercontent.com/23103201/221406562-2563022d-aa05-45f9-b64a-2a3b788b7c7a.jpg)

**Comment by caesiumstudio** [comment]
Please try the following as a way to check if something is temporarily not working - 
Solution 1 - Uninstall and reinstall again.
Solution 2 - Go to C:\Users\<UserName>\AppData\Roaming\ and delete the csBooks folder.

Let me know if this helps.. otherwise we need to find out more about what the possible cause of this hanging is.
